# Generated by Django 3.2.4 on 2021-11-20 17:30

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historiaPK', models.AutoField(primary_key=True, serialize=False)),
                ('medico_updated', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Último en Modificar')),
                ('cod_historiaclinica', models.IntegerField(verbose_name='HC')),
                ('fecha_ingresohospital', models.DateTimeField(verbose_name='Fecha de ingreso a Hospital')),
                ('fecha_ingresoarea', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ingreso a Area')),
                ('nro_cama', models.IntegerField(default=0, verbose_name='Nro. de Cama')),
                ('grado_instruccion', models.CharField(max_length=100, verbose_name='Grado Instrucción')),
                ('proviene', models.CharField(max_length=100, verbose_name='Proviene de')),
                ('antecedente', models.CharField(max_length=700, verbose_name='Antecedentes')),
                ('historia_enfermedad_actual', models.TextField(verbose_name='Historia de la Enfermedad Actual')),
                ('tension_arterial', models.CharField(default='-', max_length=30, null=True, verbose_name='TA')),
                ('frecuencia_cardiaca', models.CharField(default='-', max_length=30, null=True, verbose_name='FC')),
                ('frecuencia_respiratoria', models.CharField(default='-', max_length=30, null=True, verbose_name='FR')),
                ('temp_ax', models.CharField(default='-', max_length=30, null=True, verbose_name='TEMP AX')),
                ('sindrome_at', models.CharField(default='-', max_length=30, null=True, verbose_name='SAT')),
                ('peso', models.CharField(default='-', max_length=50, null=True, verbose_name='Peso')),
                ('piel_mucosa', models.TextField(default='-', null=True, verbose_name='Piel y Mucosas')),
                ('neurologico', models.TextField(default='-', null=True, verbose_name='Neurologico')),
                ('cardiopulmonar', models.TextField(default='-', null=True, verbose_name='Cardiopulmonar')),
                ('abdomen', models.TextField(default='-', null=True, verbose_name='Abdomen')),
                ('genitourinario', models.TextField(default='-', null=True, verbose_name='Genitourinario')),
                ('musculoesqueletico', models.TextField(default='-', null=True, verbose_name='Musculoesqueletico')),
                ('impresion_diagnostica', models.TextField(verbose_name='Impresion Diagnostica')),
                ('estado', models.CharField(default='Activo', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'HistoriaClinica',
                'verbose_name_plural': 'HistoriaClinicas',
                'db_table': 'tb_historiaclinica',
                'ordering': ['-id_historiaPK'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHistoriaClinica',
            fields=[
                ('id_historiaPK', models.IntegerField(blank=True, db_index=True)),
                ('medico_updated', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Último en Modificar')),
                ('cod_historiaclinica', models.IntegerField(verbose_name='HC')),
                ('fecha_ingresohospital', models.DateTimeField(verbose_name='Fecha de ingreso a Hospital')),
                ('fecha_ingresoarea', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ingreso a Area')),
                ('nro_cama', models.IntegerField(default=0, verbose_name='Nro. de Cama')),
                ('grado_instruccion', models.CharField(max_length=100, verbose_name='Grado Instrucción')),
                ('proviene', models.CharField(max_length=100, verbose_name='Proviene de')),
                ('antecedente', models.CharField(max_length=700, verbose_name='Antecedentes')),
                ('historia_enfermedad_actual', models.TextField(verbose_name='Historia de la Enfermedad Actual')),
                ('tension_arterial', models.CharField(default='-', max_length=30, null=True, verbose_name='TA')),
                ('frecuencia_cardiaca', models.CharField(default='-', max_length=30, null=True, verbose_name='FC')),
                ('frecuencia_respiratoria', models.CharField(default='-', max_length=30, null=True, verbose_name='FR')),
                ('temp_ax', models.CharField(default='-', max_length=30, null=True, verbose_name='TEMP AX')),
                ('sindrome_at', models.CharField(default='-', max_length=30, null=True, verbose_name='SAT')),
                ('peso', models.CharField(default='-', max_length=50, null=True, verbose_name='Peso')),
                ('piel_mucosa', models.TextField(default='-', null=True, verbose_name='Piel y Mucosas')),
                ('neurologico', models.TextField(default='-', null=True, verbose_name='Neurologico')),
                ('cardiopulmonar', models.TextField(default='-', null=True, verbose_name='Cardiopulmonar')),
                ('abdomen', models.TextField(default='-', null=True, verbose_name='Abdomen')),
                ('genitourinario', models.TextField(default='-', null=True, verbose_name='Genitourinario')),
                ('musculoesqueletico', models.TextField(default='-', null=True, verbose_name='Musculoesqueletico')),
                ('impresion_diagnostica', models.TextField(verbose_name='Impresion Diagnostica')),
                ('estado', models.CharField(default='Activo', max_length=10, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical HistoriaClinica',
                'db_table': 'audit_hc',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
