# Generated by Django 3.2.4 on 2021-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenfisico', '0002_historicalexamenfisico_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenfisico',
            name='frecuencia_cardiaca',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='FC'),
        ),
        migrations.AlterField(
            model_name='historicalexamenfisico',
            name='frecuencia_cardiaca',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='FC'),
        ),
    ]
