# Generated by Django 3.2.4 on 2021-11-20 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLab',
            fields=[
                ('id_resultadolabPK', models.AutoField(primary_key=True, serialize=False)),
                ('lab_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='GB')),
                ('lab_hb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='HB')),
                ('lab_ph', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PH')),
                ('lab_got', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='GOT')),
                ('lab_neu', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='NEU')),
                ('lab_htco', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='HTCO')),
                ('lab_pco', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PCO2')),
                ('lab_gpt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='GPT')),
                ('lab_lin', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='LIN')),
                ('lab_cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='CR')),
                ('lab_hco', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='HCO3')),
                ('lab_pt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PT')),
                ('lab_cay', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='CAY')),
                ('lab_urea', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='UREA')),
                ('lab_alb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='ALB')),
                ('lab_po', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PO2')),
                ('lab_plq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PLQ')),
                ('lab_na', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='NA')),
                ('lab_eb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='EB')),
                ('lab_cl', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='CL')),
                ('lab_k', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='K')),
                ('lab_lact', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='LACT')),
                ('lab_dd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='DD')),
            ],
            options={
                'verbose_name': 'Resultadolab',
                'verbose_name_plural': 'Resultadolabs',
                'db_table': 'tb_resultadolab',
            },
        ),
        migrations.CreateModel(
            name='HistoricalResultadoLab',
            fields=[
                ('id_resultadolabPK', models.IntegerField(blank=True, db_index=True)),
                ('lab_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='GB')),
                ('lab_hb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='HB')),
                ('lab_ph', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PH')),
                ('lab_got', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='GOT')),
                ('lab_neu', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='NEU')),
                ('lab_htco', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='HTCO')),
                ('lab_pco', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PCO2')),
                ('lab_gpt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='GPT')),
                ('lab_lin', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='LIN')),
                ('lab_cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='CR')),
                ('lab_hco', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='HCO3')),
                ('lab_pt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PT')),
                ('lab_cay', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='CAY')),
                ('lab_urea', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='UREA')),
                ('lab_alb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='ALB')),
                ('lab_po', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PO2')),
                ('lab_plq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PLQ')),
                ('lab_na', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='NA')),
                ('lab_eb', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='EB')),
                ('lab_cl', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='CL')),
                ('lab_k', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='K')),
                ('lab_lact', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='LACT')),
                ('lab_dd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='DD')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Resultadolab',
                'db_table': 'audit_result_lab',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
