# Generated by Django 3.2.4 on 2021-12-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0001_initial'),
        ('evolucion', '0002_initial'),
        ('resultadocultivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadocultivo',
            name='id_cultivoFK',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cultivo.cultivo'),
        ),
        migrations.AlterField(
            model_name='resultadocultivo',
            name='id_evolucionFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evolucion.evolucion'),
        ),
    ]
