# Generated by Django 3.2.4 on 2022-01-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultadocultivo', '0002_auto_20211202_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadocultivo',
            options={'ordering': ['-id_resultCultivoPK'], 'verbose_name': 'resultadocultivo', 'verbose_name_plural': 'resultadocultivos'},
        ),
    ]
