# Generated by Django 3.2.4 on 2021-11-20 17:30

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id_examenfisicoPK', models.AutoField(primary_key=True, serialize=False)),
                ('tension_arterial', models.CharField(blank=True, default='-', max_length=15, null=True, verbose_name='TA')),
                ('frecuencia_cardiaca', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='FC')),
                ('frecuencia_respiratoria', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='FR')),
                ('temp_ax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='TEMP AX')),
                ('sindrome_at', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='SAT')),
                ('pao', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAO-2')),
                ('fio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='FIO-2')),
                ('pao_fio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAO2/FIO2')),
                ('pas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAS')),
                ('pad', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAD')),
                ('pam', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAM')),
                ('avm', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='AVM')),
                ('modo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='MODO')),
                ('noradrenalina', models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Noradrenalina')),
                ('atracurio', models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Atracurio')),
                ('vc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='VC')),
                ('peep', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PEEP')),
                ('prono_dias', models.CharField(blank=True, default='-', max_length=15, null=True, verbose_name='Prono Días')),
                ('pi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PI')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Peso')),
                ('piel_mucosa', models.TextField(blank=True, default='-', null=True, verbose_name='Piel y Mucosas')),
                ('neurologico', models.TextField(blank=True, default='-', null=True, verbose_name='Neurologico')),
                ('cardiopulmonar', models.TextField(blank=True, default='-', null=True, verbose_name='Cardiopulmonar')),
                ('abdomen', models.TextField(blank=True, default='-', null=True, verbose_name='Abdomen')),
                ('genitourinario', models.TextField(blank=True, default='-', null=True, verbose_name='Genitourinario')),
                ('musculoesqueletico', models.TextField(blank=True, default='-', null=True, verbose_name='Musculoesqueletico')),
            ],
            options={
                'verbose_name': 'ExamenFisico',
                'verbose_name_plural': 'ExamenFisicos',
                'db_table': 'tb_examenfisico',
            },
        ),
        migrations.CreateModel(
            name='HistoricalExamenFisico',
            fields=[
                ('id_examenfisicoPK', models.IntegerField(blank=True, db_index=True)),
                ('tension_arterial', models.CharField(blank=True, default='-', max_length=15, null=True, verbose_name='TA')),
                ('frecuencia_cardiaca', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='FC')),
                ('frecuencia_respiratoria', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='FR')),
                ('temp_ax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='TEMP AX')),
                ('sindrome_at', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='SAT')),
                ('pao', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAO-2')),
                ('fio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='FIO-2')),
                ('pao_fio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAO2/FIO2')),
                ('pas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAS')),
                ('pad', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAD')),
                ('pam', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PAM')),
                ('avm', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='AVM')),
                ('modo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='MODO')),
                ('noradrenalina', models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Noradrenalina')),
                ('atracurio', models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Atracurio')),
                ('vc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='VC')),
                ('peep', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PEEP')),
                ('prono_dias', models.CharField(blank=True, default='-', max_length=15, null=True, verbose_name='Prono Días')),
                ('pi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PI')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Peso')),
                ('piel_mucosa', models.TextField(blank=True, default='-', null=True, verbose_name='Piel y Mucosas')),
                ('neurologico', models.TextField(blank=True, default='-', null=True, verbose_name='Neurologico')),
                ('cardiopulmonar', models.TextField(blank=True, default='-', null=True, verbose_name='Cardiopulmonar')),
                ('abdomen', models.TextField(blank=True, default='-', null=True, verbose_name='Abdomen')),
                ('genitourinario', models.TextField(blank=True, default='-', null=True, verbose_name='Genitourinario')),
                ('musculoesqueletico', models.TextField(blank=True, default='-', null=True, verbose_name='Musculoesqueletico')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ExamenFisico',
                'db_table': 'audit_examen_fisico',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
