# Generated by Django 3.2.4 on 2021-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedidasGenerales',
            fields=[
                ('id_medidagPK', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=600, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name': 'MedidaGeneral',
                'verbose_name_plural': 'MedidasGenerales',
                'db_table': 'tb_medidas_generales',
            },
        ),
    ]
