# Generated by Django 3.2.4 on 2021-11-20 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudLaboratorio',
            fields=[
                ('id_solicitudlabPK', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'SolicitudLab',
                'verbose_name_plural': 'SolicitudLabs',
                'db_table': 'tb_solicitudlab',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSolicitudLaboratorio',
            fields=[
                ('id_solicitudlabPK', models.IntegerField(blank=True, db_index=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(blank=True, max_length=150, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical SolicitudLab',
                'db_table': 'audit_solic_lab',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
