# Generated by Django 3.2.4 on 2021-11-20 17:30

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='det_cultivo_evolucion',
            fields=[
                ('id_det_cultivo_evolucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
            ],
            options={
                'db_table': 'det_cultivo_evolucion',
            },
        ),
        migrations.CreateModel(
            name='det_tratmiento_evolucion',
            fields=[
                ('id_det_tratamiento_evolucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('indicacion', models.CharField(default='-', max_length=500, verbose_name='Indicacion')),
            ],
            options={
                'db_table': 'det_tratamiento_evolucion',
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id_evolucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('medico_updated', models.CharField(default='-', max_length=50, verbose_name='Último en Modificar')),
                ('nro_cama', models.IntegerField(default=1, verbose_name='Nro. de Cama')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha')),
                ('dias_area', models.CharField(default='-', max_length=10, verbose_name='Dias en Areas')),
                ('diagnostico_evolucion', models.TextField(default='-', verbose_name='Diagnostico')),
                ('analisis', models.TextField(default='-', verbose_name='Análisis')),
                ('plan', models.TextField(default='-', verbose_name='Plan')),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Evolucion',
                'verbose_name_plural': 'Evoluciones',
                'db_table': 'tb_evolucion',
                'ordering': ['-id_evolucionPK'],
            },
        ),
        migrations.CreateModel(
            name='Historicaldet_cultivo_evolucion',
            fields=[
                ('id_det_cultivo_evolucionPK', models.IntegerField(blank=True, db_index=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical det_cultivo_evolucion',
                'db_table': 'audit_det_cultivo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldet_tratmiento_evolucion',
            fields=[
                ('id_det_tratamiento_evolucionPK', models.IntegerField(blank=True, db_index=True)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('indicacion', models.CharField(default='-', max_length=500, verbose_name='Indicacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical det_tratmiento_evolucion',
                'db_table': 'audit_det_tratam',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEvolucion',
            fields=[
                ('id_evolucionPK', models.IntegerField(blank=True, db_index=True)),
                ('medico_updated', models.CharField(default='-', max_length=50, verbose_name='Último en Modificar')),
                ('nro_cama', models.IntegerField(default=1, verbose_name='Nro. de Cama')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha')),
                ('dias_area', models.CharField(default='-', max_length=10, verbose_name='Dias en Areas')),
                ('diagnostico_evolucion', models.TextField(default='-', verbose_name='Diagnostico')),
                ('analisis', models.TextField(default='-', verbose_name='Análisis')),
                ('plan', models.TextField(default='-', verbose_name='Plan')),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Evolucion',
                'db_table': 'audit_evol',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
