# Generated by Django 3.2.4 on 2021-11-20 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_pacientePK', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=250, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=150, verbose_name='Apellido Materno')),
                ('nro_documento', models.IntegerField(verbose_name='Nro de Documento')),
                ('complementario_ci', models.CharField(default='-', max_length=20, verbose_name='Complement Ci')),
                ('sexo', models.CharField(max_length=2, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('ocupacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ocupación')),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Civil')),
                ('residencia', models.CharField(max_length=150, verbose_name='Residencia')),
                ('procedencia', models.CharField(max_length=150, verbose_name='Procedencia')),
                ('domicilio', models.TextField(blank=True, max_length=600, null=True, verbose_name='Domicilio')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('nombre_referencia', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre Referencia')),
                ('telefono_referencia', models.IntegerField(blank=True, null=True, verbose_name='Telefono Referencia')),
                ('vacuna_covid', models.CharField(default='No', max_length=30, verbose_name='Vacuna - Covid 19')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'tb_paciente',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaciente',
            fields=[
                ('id_pacientePK', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=250, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=150, verbose_name='Apellido Materno')),
                ('nro_documento', models.IntegerField(verbose_name='Nro de Documento')),
                ('complementario_ci', models.CharField(default='-', max_length=20, verbose_name='Complement Ci')),
                ('sexo', models.CharField(max_length=2, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('ocupacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ocupación')),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Civil')),
                ('residencia', models.CharField(max_length=150, verbose_name='Residencia')),
                ('procedencia', models.CharField(max_length=150, verbose_name='Procedencia')),
                ('domicilio', models.TextField(blank=True, max_length=600, null=True, verbose_name='Domicilio')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('nombre_referencia', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre Referencia')),
                ('telefono_referencia', models.IntegerField(blank=True, null=True, verbose_name='Telefono Referencia')),
                ('vacuna_covid', models.CharField(default='No', max_length=30, verbose_name='Vacuna - Covid 19')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Paciente',
                'db_table': 'audit_paciente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
