# Generated by Django 3.2.4 on 2021-11-20 17:30

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evolucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='det_indicacion_medida_general',
            fields=[
                ('id_det_indicacion_medidaPK', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'det_indicacion_medida_general',
            },
        ),
        migrations.CreateModel(
            name='det_solicitud_indicacion',
            fields=[
                ('id_det_solicitud_indicacionPK', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha Solicitud')),
            ],
            options={
                'db_table': 'det_solicitud_indicacion',
            },
        ),
        migrations.CreateModel(
            name='det_solucion',
            fields=[
                ('id_det_solucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('indicacion', models.TextField(blank=True, max_length=200, null=True, verbose_name='Indicacion')),
                ('via_admin', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Via de Administración')),
            ],
            options={
                'db_table': 'det_solucion_nombresolucion',
            },
        ),
        migrations.CreateModel(
            name='det_tratamiento_indicacion',
            fields=[
                ('id_det_tratamiento_indicacionPK', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('indicacion', models.CharField(default='-', max_length=500, verbose_name='Indicacion')),
                ('via_admin', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Via de Administración')),
            ],
            options={
                'db_table': 'det_tratamiento_indicacion',
            },
        ),
        migrations.CreateModel(
            name='Historicaldet_indicacion_medida_general',
            fields=[
                ('id_det_indicacion_medidaPK', models.IntegerField(blank=True, db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical det_indicacion_medida_general',
                'db_table': 'audit_det_indic_medida',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldet_solicitud_indicacion',
            fields=[
                ('id_det_solicitud_indicacionPK', models.IntegerField(blank=True, db_index=True)),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical det_solicitud_indicacion',
                'db_table': 'audit_det_indic_solic',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldet_solucion',
            fields=[
                ('id_det_solucionPK', models.IntegerField(blank=True, db_index=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('indicacion', models.TextField(blank=True, max_length=200, null=True, verbose_name='Indicacion')),
                ('via_admin', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Via de Administración')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical det_solucion',
                'db_table': 'audit_det_indic_soluc',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldet_tratamiento_indicacion',
            fields=[
                ('id_det_tratamiento_indicacionPK', models.IntegerField(blank=True, db_index=True)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('indicacion', models.CharField(default='-', max_length=500, verbose_name='Indicacion')),
                ('via_admin', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Via de Administración')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical det_tratamiento_indicacion',
                'db_table': 'audit_det_indic_tratam',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicacion',
            fields=[
                ('id_indicacionPK', models.IntegerField(blank=True, db_index=True)),
                ('medico_updated', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Último en Modificar')),
                ('fecha_indicacion', models.DateField()),
                ('dieta', models.TextField(blank=True, null=True, verbose_name='Dieta')),
                ('terapia_respiratoria', models.TextField(blank=True, null=True, verbose_name='Terapia Respiratoria')),
                ('estado', models.CharField(default='Activo', max_length=10, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Indicacion',
                'db_table': 'audit_indicacion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Indicacion',
            fields=[
                ('id_indicacionPK', models.AutoField(primary_key=True, serialize=False)),
                ('medico_updated', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Último en Modificar')),
                ('fecha_indicacion', models.DateField()),
                ('dieta', models.TextField(blank=True, null=True, verbose_name='Dieta')),
                ('terapia_respiratoria', models.TextField(blank=True, null=True, verbose_name='Terapia Respiratoria')),
                ('estado', models.CharField(default='Activo', max_length=10, verbose_name='Estado')),
                ('id_evolucionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evolucion.evolucion')),
            ],
            options={
                'verbose_name': 'Indicacion',
                'verbose_name_plural': 'Indicaciones',
                'db_table': 'tb_indicacion',
            },
        ),
    ]
